import utime
from pyControl.utility import *
import hardware_definition as hw
from devices import *

# -------------------------------------------------------------------------
# Variables
# -------------------------------------------------------------------------
v.motion_threshold = 10      # Sensitivity of the motion sensor
v.refractory_period = 2 * second  # Time to ignore motion after triggering stimulation
                                  # (Should be >= the duration in your Python script)

# -------------------------------------------------------------------------
# States and Events
# -------------------------------------------------------------------------
states = [
    'monitoring',
    'triggered_refractory'
]

events = [
    'motion',   # Event generated by the RotaryEncoder/MotionSensor
    'timer_refractory'
]

initial_state = 'monitoring'

# -------------------------------------------------------------------------
# Run Start/End
# -------------------------------------------------------------------------
def run_start():
    print('{}, Task Started. Initializing Motion Sensor...'.format(get_current_time()))
    
    # 1. Setup Motion Sensor
    if hasattr(hw, 'motionSensor'):
        hw.motionSensor.record()
        hw.motionSensor.threshold = v.motion_threshold
    else:
        print("!! Error: 'motionSensor' not found in hardware_definition.")

    # 2. Send 0: Signal Session Start
    if hasattr(hw, 'bci_link'):
        hw.bci_link.send_int(0) 
        print(">> Sent [0] (Session Start) via UART")

def run_end():
    # 1. Stop Motion Sensor
    if hasattr(hw, 'motionSensor'):
        hw.motionSensor.stop()
        hw.motionSensor.off()

    # 2. Send 0: Signal Session End
    if hasattr(hw, 'bci_link'):
        hw.bci_link.send_int(0)
        print(">> Sent [0] (Session End) via UART")
    
    print('{}, Run End.'.format(get_current_time()))

# -------------------------------------------------------------------------
# State Machine
# -------------------------------------------------------------------------

def monitoring(event):
    """
    Idle state: actively listening for motion events.
    """
    if event == 'entry':
        print('{}, Monitoring for motion...'.format(get_current_time()))
        
    elif event == 'motion':
        # Motion threshold crossed -> Trigger Stimulation
        goto_state('triggered_refractory')

def triggered_refractory(event):
    """
    Sends the trigger, then waits for v.refractory_period.
    Any motion detected during this time is ignored to prevent
    overlapping stimulation commands.
    """
    if event == 'entry':
        # 1. Send Trigger
        if hasattr(hw, 'bci_link'):
            hw.bci_link.send_int(1)
            print(">> Motion Detected! Sent [1] via UART")
        
        # 2. Wait (Refractory Period)
        # This prevents sending triggers faster than the Python script can handle
        timed_goto_state('monitoring', v.refractory_period)
        
    elif event == 'motion':
        # Optional: Print that we are ignoring motion while stimulating
        # print("Ignoring motion during stimulation...")
        pass