from pyControl.hardware import *
from pyb import UART
from machine import Timer

class USB_UART(IO_object):
    def __init__(self, name):
        self.uart = UART(1, 9600)                         # init with given baudrate
        self.uart.init(9600, bits=8, parity=None, stop=1) # init with given parameters
        # self.timer = Timer(3)
        # self.timer.init(mode=Timer.PERIODIC)
        # self.timer_ch = self.timer.channel(Timer.A, freq=5)
        # self.timer_ch.irq(handler=self._timer_ISR, trigger=Timer.TIMEOUT)
        self.buffer = bytearray(8)
        self.name = name
        assign_ID(self)
        # Data acqisition variables
        self.timer = pyb.Timer(available_timers.pop())
        self.timestamp = fw.current_time
        self.output = -1.0

    def _timer_ISR(self, t):
        if self.uart.any() > 0:
            self.uart.readinto(self.buffer, 2)
            self.output = float(int.from_bytes(self.buffer, 'little'))
        else:
            self.output = -1.0
        self.timestamp = fw.current_time
        interrupt_queue.put(self.ID)
    
    def start_test(self):
        self.timer.init(freq=100)   # this should be 2*(client frequency)
        self.timer.callback(self._timer_ISR)
       
    def _initialise(self):
        pass

    def _run_start(self):
        pass

    def _run_stop(self):
        pass

    def off(self):
        pass
    
    def _process_interrupt(self):
        # Put event generated by threshold crossing in event queue.
        fw.event_queue.put((self.timestamp, fw.event_typ, fw.events[self.name]))